### ISSUE TITLE
Deploy ELIXIR - REMS proxy on OpenShift a.k.a. Rahti

### ISSUE THREAD

**Issue by blankdots** [CSCfi/elixir-rems-proxy#1]
#### Description
We would like to deploy this Proxy on OpenShift in order for ELIXIR to make the integration

#### DoD
REMS proxy deployed at rahti.csc.fi

#### Testing 
Proxy still keeps functionality.

**Comment by teemukataja** [comment]
Deployed proxy to `rahti.csc.fi` which contacts REMS at another location.
```
curl -X GET \
  'http://proxy-elixir-rems-proxy.rahtiapp.fi/entitlements?user=alice' \
  -H 'api-key: 42' \
  -H 'elixir-id: developer'
```

**Comment by blankdots** [comment]
Done :heavy_check_mark:
